spring:
#  jwt:
  #    secret: SeguraOGrosso
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    password: 1234db
    testWhileIdle: true
    url: jdbc:mariadb://localhost:3306/dbCarBurguer?createDatabaseIfNotExist=true
    username: root
    validationQuery: SELECT 1
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
